// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVem5r52zgFJF1_kS_FNcYOpr62kI71U',
    appId: '1:301978139870:web:304e042648da5aa9b8164f',
    messagingSenderId: '301978139870',
    projectId: 'orbriot',
    authDomain: 'orbriot.firebaseapp.com',
    storageBucket: 'orbriot.firebasestorage.app',
    measurementId: 'G-6ESFLCW0CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChaMEWBwfbMRROJDMwSMcAixyrCBDYD40',
    appId: '1:301978139870:android:cd26311d4fff4bc6b8164f',
    messagingSenderId: '301978139870',
    projectId: 'orbriot',
    storageBucket: 'orbriot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqXOAjJiAXv-wkE8I6mnbVi78FkGVjWk',
    appId: '1:301978139870:ios:528296d9385f0257b8164f',
    messagingSenderId: '301978139870',
    projectId: 'orbriot',
    storageBucket: 'orbriot.firebasestorage.app',
    iosBundleId: 'com.erdogdu.orbriot',
  );
}
